# Generated by Django 4.2.3 on 2023-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_alter_restaurant_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='imageUrl',
            field=models.CharField(max_length=500),
        ),
    ]
